apiVersion: v1
kind: Secret
metadata:
  name: {{ include "daytrader-web.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "daytrader-web.name" . }}
    helm.sh/chart: {{ include "daytrader-web.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  tls.crt: {{ required ".Values.secrets.tls.crt is required" .Values.secrets.tls.crt | quote }}
  tls.key: {{ required ".Values.secrets.tls.key is required" .Values.secrets.tls.key | quote }}
type: kubernetes.io/tls
